Include compiled mod files.
BlueBrain/nmodl pull request #1131
Opened 2023-12-20 09:04 UTC by 1uc

Add a script for generating the reference values of compiled mod files. These are included with the sources to enable the following:

  * during review the reviewer can see what was generated.
  * these can serve as golden tests, flagging changes in unrelated mod files.

2023-12-20 09:04 UTC, 1uc commented on test/usecases/cnexp_scalar/leonhard.cpp
> +NMODL Compiler  : 0.6 [e35b3dfb 2023-12-14 23:06:50 +0100]
Will need to be wiped from the reference.

2023-12-20 09:05 UTC, 1uc commented on test/usecases/cnexp_scalar/leonhard.cpp
> +Created         : Wed Dec 20 09:37:50 2023
Will need to be wiped from the reference.

2023-12-20 09:14 UTC, 1uc commented
The hope is that it can generate a suite of references. Then when things change we have `diff` to print exactly which lines changed, probably we can get it to print which characters changed too.

The advantage is that we can automatically update the references; and don't need to do so manually. The cost is that we need to commit entire files. Meaning we test the whole file not just the "interesting" parts of each usecase. Which means we're sensitive to more changes.

2024-01-09 19:51 UTC, iomaganaris requested changes
Those "golden" reference files could be a potential solution. However I think that this PR is missing a test that compares the "golden" reference file with the one generated using the NMODL being tested.
Let's discuss this with @pramodk and @ohm314 to see what Omar has been working on to make the diff of these "golden" reference files nicer and see how to proceed

2024-01-10 07:56 UTC, 1uc commented
Yes, I agree. In a first step I'd like to understand if it helps with my difficulty reviewing PRs. While I can see what changed and might understand at a high-level what's happening, I can't see the generated code. The question is: does seeing how the generated code changed help understand a PR?

I suspect this might help with that. As for checking/diffing: fist time they're uploaded the references are completely new. After that the diff will only contain the lines that change due to a specific PR. Preferably one would add the file in a separate commit. Before any changes. Then make changes and have the diff already valid on the first PR.

2024-01-10 16:52 UTC, iomaganaris commented
> The question is: does seeing how the generated code changed help understand a PR?

It definitely helps :+1: 

> After that the diff will only contain the lines that change due to a specific PR. Preferably one would add the file in a separate commit. Before any changes. Then make changes and have the diff already valid on the first PR.

I am afraid that with so many files we are going to start forgetting to update them in case there are any changes or miss small changes to them. I believe it's necessary to have a way to automatically update them when opening a PR with some changes. Once way to enforce that is to have a test that fails if there is a difference between the generated and the "golden" file.

2024-02-07 16:09 UTC, 1uc commented on test/usecases/cnexp_scalar/leonhard.cpp
> +NMODL Compiler  : 0.6 [e35b3dfb 2023-12-14 23:06:50 +0100]
solved

2024-02-07 16:09 UTC, 1uc commented on test/usecases/cnexp_scalar/leonhard.cpp
> +Created         : Wed Dec 20 09:37:50 2023
solved

2024-02-09 11:08 UTC, pramodk commented
@1uc : I assume this will be updated by pushing references to https://github.com/BlueBrain/nmodl-references. So I will keep this as it is.

2024-02-09 12:44 UTC, 1uc commented
Yes, exactly.

2024-02-20 15:17 UTC, 1uc commented
@pramodk the generated files have been move to the submodule. there's a PR ready in the submodule:
https://github.com/BlueBrain/nmodl-references/pull/1

2024-02-22 09:05 UTC, 1uc commented
Finally: https://github.com/BlueBrain/nmodl/actions/runs/8001921784/job/21854083478?pr=1131#step:15:245

2024-02-22 15:03 UTC, 1uc commented
The proposed tests fail as follows:
```
$ ctest --test-dir TEST_DIR --output-on-failure
...
[NMODL] [info] :: Running C++ backend code generator for CoreNEURON
diff -r /home/lucg/git/bbp/nmodl/test/usecases/references/func_proc_pnt/neuron/func_proc_pnt.cpp /tmp/tmp.PQmpGOAFU8/neuron/func_proc_pnt.cpp
84a85,87
>         int const * _nodeindices;
>         double const * _node_voltages;
>         double * _node_rhs;
92c95
<     static test_func_proc_pnt_Instance make_instance_test_func_proc_pnt(_nrn_mechanism_cache_range& _ml) {
---
>     static test_func_proc_pnt_Instance make_instance_test_func_proc_pnt(_nrn_mechanism_cache_range& _ml, NrnThread& _nt, Memb_list& _ml_arg) {
93a97,99
>             _ml_arg.nodeindices,
>             _nt.node_voltage_storage(),
>             _nt.node_rhs_storage(),
146,148c152,154
<     inline double get_a_42_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt, double a);
<     inline int set_x_42_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt);
<     inline int set_x_a_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt, double a);
---
>     inline double get_a_42_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v, double a);
>     inline int set_x_42_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v);
>     inline int set_x_a_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v, double a);
199c205
<         set_x_42_test_func_proc_pnt(_ml, id, _ppvar, _thread, _nt);
---
>         set_x_42_test_func_proc_pnt(id, inst, v);
219c225
<         set_x_a_test_func_proc_pnt(_ml, id, _ppvar, _thread, _nt, *getarg(1));
---
>         set_x_a_test_func_proc_pnt(id, inst, v, *getarg(1));
238c244
<         _r = get_a_42_test_func_proc_pnt(_ml, id, _ppvar, _thread, _nt, *getarg(1));
---
>         _r = get_a_42_test_func_proc_pnt(id, inst, v, *getarg(1));
243,244c249,250
<     inline int set_x_42_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt) {
<         auto inst = make_instance_test_func_proc_pnt(*_ml);
---
>     inline int set_x_42_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v) {
>         auto inst = make_instance_test_func_proc_pnt(*_ml, *_nt, *_ml_arg);
251,252c257,258
<     inline int set_x_a_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt, double a) {
<         auto inst = make_instance_test_func_proc_pnt(*_ml);
---
>     inline int set_x_a_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v, double a) {
>         auto inst = make_instance_test_func_proc_pnt(*_ml, *_nt, *_ml_arg);
259,260c265,266
<     inline double get_a_42_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt, double a) {
<         auto inst = make_instance_test_func_proc_pnt(*_ml);
---
>     inline double get_a_42_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v, double a) {
>         auto inst = make_instance_test_func_proc_pnt(*_ml, *_nt, *_ml_arg);
269c275
<         auto inst = make_instance_test_func_proc_pnt(_lmr);
---
>         auto inst = make_instance_test_func_proc_pnt(_lmr, *_nt, *_ml_arg);
```

2024-02-22 15:05 UTC, 1uc commented
The unit-test fail as follows:
```
 18/126 Test  #18: testcodegen/Scenario: Check NEURON codegen for simple MOD file ......................................***Failed    0.03 sec
Filters: "Scenario: Check NEURON codegen for simple MOD file"
Randomness seeded to: 3724744856

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
testcodegen is a Catch2 v3.3.2 host application.
Run with -? for options

-------------------------------------------------------------------------------
Scenario: Check NEURON codegen for simple MOD file
      Given: A simple mod file with RANGE, ARRAY and ION variables
       Then: Correct pas_test_Instance
-------------------------------------------------------------------------------
/home/lucg/git/bbp/nmodl/test/unit/codegen/codegen_neuron_cpp_visitor.cpp:186
...............................................................................

/home/lucg/git/bbp/nmodl/test/unit/codegen/codegen_neuron_cpp_visitor.cpp:205: FAILED:
  REQUIRE_THAT( generated, ContainsSubstring(reindent_and_trim_text(expected)) )
with expansion:
  "/*********************************************************
  Model Name      : pas_test
  Filename        : _test.mod
  NMODL Version   : 7.7.0
  Vectorized      : true
  Threadsafe      : true
  Created         : Thu Feb 22 15:59:48 2024
  Simulator       : NEURON
  Backend         : C++ (api-compatibility)
  NMODL Compiler  : 0.6 [eb3215b7 2024-02-22 15:59:27 +0100]
  *********************************************************/
  
#include <math.h>
  #include <stdio.h>
  #include <stdlib.h>
  
#include "mech_api.h"
  #include "neuron/cache/mechanism_range.hpp"
  #include "nrniv_mf.h"
  #include "section_fwd.hpp"
  
/* NEURON global macro definitions */
  /* VECTORIZED */
  #define NRN_VECTORIZED 1
  
static constexpr auto number_of_datum_variables = 3;
  static constexpr auto number_of_floating_point_variables = 10;
  
namespace {
  template <typename T>
  using _nrn_mechanism_std_vector = std::vector<T>;
  using _nrn_model_sorted_token = neuron::model_sorted_token;
  using _nrn_mechanism_cache_range = neuron::cache::MechanismRange
  <number_of_floating_point_variables, number_of_datum_variables>;
  using _nrn_mechanism_cache_instance = neuron::cache::MechanismInstance
  <number_of_floating_point_variables, number_of_datum_variables>;
  using _nrn_non_owning_id_without_container = neuron::container::
  non_owning_identifier_without_container;
  template <typename T>
  using _nrn_mechanism_field = neuron::mechanism::field<T>;
  template <typename... Args>
  void _nrn_mechanism_register_data_fields(Args&&... args) {
      neuron::mechanism::register_data_fields(std::forward<Args>(args)...);
  }
  }  // namespace
  
Prop* hoc_getdata_range(int type);
  

  namespace neuron {
      #ifndef NRN_PRCELLSTATE
      #define NRN_PRCELLSTATE 0
      #endif
  

      /** channel information */
      static const char *mechanism_info[] = {
          "7.7.0",
          "pas_test",
          "g_pas_test",
          "e_pas_test",
          0,
          "i_pas_test",
          "ar_pas_test[2]",
          0,
          "s_pas_test",
          0,
          0
      };
  

      /* NEURON global variables */
      static neuron::container::field_index _slist1[1], _dlist1[1];
      static Symbol* _na_sym;
      static int mech_type;
      static Prop* _extcall_prop;
      /* _prop_id kind of shadows _extcall_prop to allow validity checking. */
      static _nrn_non_owning_id_without_container _prop_id{};
      static int hoc_nrnpointerindex = -1;
      static _nrn_mechanism_std_vector<Datum> _extcall_thread;
  

      /** all global variables */
      struct pas_test_Store {
          double s0{};
      };
      static_assert(std::is_trivially_copy_constructible_v<pas_test_Store>);
      static_assert(std::is_trivially_move_constructible_v<pas_test_Store>);
      static_assert(std::is_trivially_copy_assignable_v<pas_test_Store>);
      static_assert(std::is_trivially_move_assignable_v<pas_test_Store>);
      static_assert(std::is_trivially_destructible_v<pas_test_Store>);
      pas_test_Store pas_test_global;
  

      /** all mechanism instance variables and global variables */
      struct pas_test_Instance  {
          int const * _nodeindices;
          double const * _node_voltages;
          double * _node_rhs;
          double* g{};
          double* e{};
          double* i{};
          double* ar{};
          double* s{};
          double* ena{};
          double* ina{};
          double* Ds{};
          double* v_unused{};
          double* g_unused{};
          const double* const* ion_ena{};
          double* const* ion_ina{};
          double* const* ion_dinadv{};
          pas_test_Store* global{&pas_test_global};
      };
  

      static pas_test_Instance make_instance_pas_test
  (_nrn_mechanism_cache_range& _ml, NrnThread& _nt, Memb_list& _ml_arg) {
          return pas_test_Instance {
              _ml_arg.nodeindices,
              _nt.node_voltage_storage(),
              _nt.node_rhs_storage(),
              _ml.template fpfield_ptr<0>(),
              _ml.template fpfield_ptr<1>(),
              _ml.template fpfield_ptr<2>(),
              _ml.template data_array_ptr<3, 2>(),
              _ml.template fpfield_ptr<4>(),
              _ml.template fpfield_ptr<5>(),
              _ml.template fpfield_ptr<6>(),
              _ml.template fpfield_ptr<7>(),
              _ml.template fpfield_ptr<8>(),
              _ml.template fpfield_ptr<9>(),
              _ml.template dptr_field_ptr<0>(),
              _ml.template dptr_field_ptr<1>(),
              _ml.template dptr_field_ptr<2>()
          };
      }
  

      static void nrn_alloc_pas_test(Prop* _prop) {
          Prop *prop_ion{};
          Datum *_ppvar{};
          _ppvar = nrn_prop_datum_alloc(mech_type, 3, _prop);
          _nrn_mechanism_access_dparam(_prop) = _ppvar;
          _nrn_mechanism_cache_instance _ml_real{_prop};
          auto* const _ml = &_ml_real;
          size_t const _iml{};
          assert(_nrn_mechanism_get_num_vars(_prop) == 10);
          /*initialize range parameters*/
          _ml->template fpfield<0>(_iml) = 0.001; /* g */
          _ml->template fpfield<1>(_iml) = -70; /* e */
          _nrn_mechanism_access_dparam(_prop) = _ppvar;
          Symbol * na_sym = hoc_lookup("na_ion");
          Prop * na_prop = need_memb(na_sym);
          _ppvar[0] = _nrn_mechanism_get_param_handle(na_prop, 0);
          _ppvar[1] = _nrn_mechanism_get_param_handle(na_prop, 3);
      }
  

      /* Neuron setdata functions */
      extern void _nrn_setdata_reg(int, void(*)(Prop*));
      static void _setdata(Prop* _prop) {
          _extcall_prop = _prop;
          _prop_id = _nrn_get_prop_id(_prop);
      }
      static void _hoc_setdata() {
          Prop *_prop = hoc_getdata_range(mech_type);
          _setdata(_prop);
          hoc_retpushx(1.);
      }
      /* Mechanism procedures and functions */
  

      /** connect global (scalar) variables to hoc -- */
      static DoubScal hoc_scalar_double[] = {
          {nullptr, nullptr}
      };
  

      /** connect global (array) variables to hoc -- */
      static DoubVec hoc_vector_double[] = {
          {nullptr, nullptr, 0}
      };
  

      /* declaration of user functions */
  

      /* connect user functions to hoc names */
      static VoidFunc hoc_intfunc[] = {
          {"setdata_pas_test", _hoc_setdata},
          {0, 0}
      };
      static NPyDirectMechFunc npy_direct_func_proc[] = {
      };
  

      void nrn_init_pas_test(_nrn_model_sorted_token const& _sorted_token,
  NrnThread* _nt, Memb_list* _ml_arg, int _type) {
          _nrn_mechanism_cache_range _lmr{_sorted_token, *_nt, *_ml_arg, _type}
  ;
          auto inst = make_instance_pas_test(_lmr, *_nt, *_ml_arg);
          auto nodecount = _ml_arg->nodecount;
          for (int id = 0; id < nodecount; id++) {
              inst.ena[id] = (*inst.ion_ena[id]);
              (inst.ar+id*2)[stati [...]

2024-02-22 15:11 UTC, 1uc commented
The diff based approach isn't stellar, but at least I can:
* see which lines changed,
* open the original reference file,
* easily obtain a file containing the generated code with the current version of nmodl.

2024-02-22 15:16 UTC, 1uc commented
I think the unit-test approach would not be sensitive to this change (which is interesting):
```
>     inline int set_x_42_test_func_proc_pnt(size_t id, test_func_proc_pnt_Instance& inst, double v) {
>         auto inst = make_instance_test_func_proc_pnt(*_ml, *_nt, *_ml_arg);
251,252c257,258
<     inline int set_x_a_test_func_proc_pnt(_nrn_mechanism_cache_range* _ml, size_t id, Datum* _ppvar, Datum* _thread, NrnThread* _nt, double a) {
<         auto inst = make_instance_test_func_proc_pnt(*_ml);
```

2024-02-22 15:31 UTC, 1uc commented
The ugly format can easily be fixed. Yielding the following output:
```
diff -U 8 -r /home/lucg/git/bbp/nmodl/test/usecases/references/func_proc_pnt/neuron/func_proc_pnt.cpp /tmp/tmp.uWHctFHaFr/neuron/func_proc_pnt.cpp
--- /home/lucg/git/bbp/nmodl/test/usecases/references/func_proc_pnt/neuron/func_proc_pnt.cpp	2024-02-22 15:58:05.526563379 +0100
+++ /tmp/tmp.uWHctFHaFr/neuron/func_proc_pnt.cpp	2024-02-22 16:29:47.645989010 +0100
@@ -77,25 +77,31 @@
     static_assert(std::is_trivially_copy_assignable_v<test_func_proc_pnt_Store>);
     static_assert(std::is_trivially_move_assignable_v<test_func_proc_pnt_Store>);
     static_assert(std::is_trivially_destructible_v<test_func_proc_pnt_Store>);
     test_func_proc_pnt_Store test_func_proc_pnt_global;
 
 
     /** all mechanism instance variables and global variables */
     struct test_func_proc_pnt_Instance  {
+        int const * _nodeindices;
+        double const * _node_voltages;
+        double * _node_rhs;
         double* x{};
         double* v_unused{};
         const double* const* node_area{};
         test_func_proc_pnt_Store* global{&test_func_proc_pnt_global};
     };
 
 
-    static test_func_proc_pnt_Instance make_instance_test_func_proc_pnt(_nrn_mechanism_cache_range& _ml) {
+    static test_func_proc_pnt_Instance make_instance_test_func_proc_pnt(_nrn_mechanism_cache_range& _ml, NrnThread& _nt, Memb_list& _ml_arg) {
         return test_func_proc_pnt_Instance {
+            _ml_arg.nodeindices,
+            _nt.node_voltage_storage(),
+            _nt.node_rhs_storage(),
             _ml.template fpfield_ptr<0>(),
             _ml.template fpfield_ptr<1>(),
             _ml.template dptr_field_ptr<0>()
         };
     }
 
 
     static void nrn_alloc_test_func_proc_pnt(Prop* _prop) {
@@ -138,19 +144,19 @@
...
```

2024-02-23 10:21 UTC, 1uc commented
We can now precisely point out issues, e.g. here:
https://github.com/BlueBrain/nmodl/issues/1168

2024-02-26 07:21 UTC, JCGoran commented on .gitmodules
> +	branch = 1uc/sketch-golden-tests
Should this be omitted maybe (I only see `main` in that repo)?

2024-02-26 08:07 UTC, 1uc commented on test/usecases/generate_references.sh
> +    sed -i "s/NMODL Compiler  : .*$/NMODL Compiler  : VERSION/" "$f"
Thanks! I don't remember CI being red. If how why isn't it picking this up?

2024-02-27 09:55 UTC, JCGoran commented on test/usecases/CMakeLists.txt
> +  if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/references/${usecase}/_does_not_exist_weiohbge)
What's the purpose of the `_does_not_exist` variable here?

2024-02-27 15:59 UTC, merged