fix for #52: solve parser error on numbers with leading +
BlueBrain/nmodl pull request #419
Opened 2020-11-06 16:10 UTC by WeinaJi

2020-11-09 10:18 UTC, WeinaJi commented
please retest

2020-11-18 09:48 UTC, ohm314 commented
please retest

2020-11-19 09:22 UTC, WeinaJi commented
please retest

2020-11-19 13:47 UTC, ohm314 approved these changes
lgtm

2020-11-19 21:00 UTC, pramodk requested changes
LGTM.
@WeinaJi : we should one test that checks this rule. See below file where we add nmodl constructs for testing : https://github.com/BlueBrain/nmodl/blob/6d39a657b8908933875f2f09b7dede3a9748757b/test/unit/utils/nmodl_constructs.cpp#L189

2020-11-19 21:00 UTC, pramodk commented on src/parser/nmodl.yy
> +                |   "+" NUMBER
@nrnhines : out of curiosity : for any reason this rule wasn't there in original implementation?

2020-11-20 14:48 UTC, WeinaJi commented
> LGTM.
> @WeinaJi : we should one test that checks this rule. See below file where we add nmodl constructs for testing :
> 
> https://github.com/BlueBrain/nmodl/blob/6d39a657b8908933875f2f09b7dede3a9748757b/test/unit/utils/nmodl_constructs.cpp#L189

@pramodk hmm... there is one issue with test case ```testvisitor/Scenario: Convert AST back to NMODL form```
The "+" sign is removed after passing so when converting back to NMODL, the generated text doesn't match the origin format. I think that's expected, but how can I solve the matching error ?

2020-11-27 09:56 UTC, pramodk commented
Sorry, missed your comment.

In that case you can pass an additional argument with the expected nmodl text. See e.g. https://github.com/BlueBrain/nmodl/blob/6d39a657b8908933875f2f09b7dede3a9748757b/test/unit/utils/nmodl_constructs.cpp#L396

2020-11-27 22:15 UTC, pramodk approved these changes

2020-11-27 22:17 UTC, merged

2020-11-27 22:17 UTC, pramodk commented
thanks @WeinaJi !