Make sure data presence block is closed in destructors
BlueBrain/nmodl pull request #651
Opened 2021-05-17 15:56 UTC by olupton

Without this change then with the OpenACC backend a closing brace is omitted:
```c++
void nrn_destructor_hh(NrnThread* nt, Memb_list* ml, int type) {
  #pragma acc data present(nt, ml, hh_global)
  {
    int nodecount = ml->nodecount;
    // ...
  } // this one was not printed
}
```
This breaks compilation of NEURON + CoreNEURON + NMODL with GPU support enabled.

2021-05-17 16:19 UTC, alkino approved these changes

2021-05-17 16:37 UTC, pramodk requested changes
@alkino  : `CONSTRUCTOR` & `DESTRUCTOR` blocks are mostly for allocation/initialisation & deallocation/finalization. They don't have anything to run on GPU. So for these two `BlockType` , we can skip calling `print_kernel_data_present_annotation_block_begin()` in `void CodegenCVisitor::print_global_function_common_code()`.

2021-05-19 14:59 UTC, pramodk commented
@olupton : do you want to update the PR wit above suggestion? (it's straightforward otherwise I can do as well!)

2021-05-19 15:11 UTC, olupton commented
I pushed the change, note that there is not a `Constructor` value for `BlockType` at the moment.

2021-05-19 15:52 UTC, pramodk approved these changes

2021-05-20 08:55 UTC, merged