Develop semantic analysis
BlueBrain/nmodl pull request #772
Opened 2021-11-08 21:40 UTC by alkino

- Add an option --static-analysis to nmodl to only run it.
- If this option is set critical errors will not throw and the program will continue
- Use log system instead of only throw
- Add a new check: destructor blocks only in point process type mod file

2021-11-22 13:25 UTC, alkino commented
@iomaganaris should we throw or only send message?

2021-11-22 15:52 UTC, iomaganaris commented
> @iomaganaris should we throw or only send message?

Discussed offline. I suggested mimicking the behavior of `CodegenCompatibilityVisitor` (just printing warnings and returning 1 from the main function)

2021-11-23 14:10 UTC, iomaganaris reviewed
LGTM in general.
Small nitpicks and suggestions

2021-11-23 17:31 UTC, pramodk requested changes

2021-11-23 17:31 UTC, pramodk commented on test/unit/visitor/semantic_analysis.cpp
> +            }
adapt this test to have `DESTRUCTOR` before`NEURON` block.

2021-11-23 18:33 UTC, pramodk commented on src/visitors/semantic_analysis_visitor.cpp
>      }
If we have mod file containing `DESTRUCTOR` block before `NEURON` block:

```
DESTRUCTOR {

}

NEURON {
    THREADSAFE
    :POINT_PROCESS test
    SUFFIX test
}
```

above implementation wouldn't work. I would suggest to set `is_point_process` in `::check()` method (e.g. by looking up for `Suffix` node type in the whole AST)

2021-11-26 07:52 UTC, pramodk approved these changes
LGTM

2021-11-26 07:55 UTC, merged